### PR TITLE
rpi-firmware/userland bump to latest

### PR DESCRIPTION
**Pull request by mobileoverlord**
rpi-firmware 1.20200527
rpi-userland f97b1af1b3e653f9da2c1a3643479bfd469e3b74

Tested on rpi3a w/wifi

### CODE REVIEW

**Comment by fhunleth** [comment]
Did you want to upgrade to Linux 5.4?

The 1.20200527 tag is a 5.4 kernel tag.
The 1.20200601 tag is a 4.19 kernel tag.

See https://github.com/raspberrypi/firmware/tree/1.20200601 and https://github.com/raspberrypi/linux/tree/raspberrypi-kernel_1.20200601-1.

**Comment by fhunleth** [comment]
This thread on the Raspberry Pi forum may be informative: https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=269769.

**Comment by mobileoverlord** [comment]
Oh wow, this is tempting:

> 5.4 also includes the kms driver for Pi4

The rest of that post is riddled with dragons. I see the value in the desire to "do as raspbian does" as the 4.19 kernel is a more stable base for people shipping devices. I'll update this to ship the 4.19 firmware, maybe we can revisit this to offer a way to switch in the defconfig to further experimentation with the Pi4's graphics.

**Comment by fhunleth** [comment]
I'm not sure that 5.4 kms is necessarily a big deal. With 4.19, you can still use KMS, but you have to use the RPi4's fkms (f=firmware) drivers. From a user's perspective, does this change anything besides deleting a bunch of f's?

**Pull request merged**
